// <auto-generated />
using System;
using Akıllı_Kütüphane_Yönetim_Sistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Akıllı_Kütüphane_Yönetim_Sistemi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251214172316_DbBaglama")]
    partial class DbBaglama
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Akıllı_Kütüphane_Yönetim_Sistemi.db_vs_sinif.Ceza", b =>
                {
                    b.Property<int>("CezaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CezaID"));

                    b.Property<decimal?>("CezaTutari")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("GecikmeGunSayisi")
                        .HasColumnType("int");

                    b.Property<int?>("IslemID")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("OdendiMi")
                        .HasColumnType("bit");

                    b.HasKey("CezaID");

                    b.ToTable("TabloCeza");
                });

            modelBuilder.Entity("Akıllı_Kütüphane_Yönetim_Sistemi.db_vs_sinif.Kitap", b =>
                {
                    b.Property<int>("KitapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KitapID"));

                    b.Property<int?>("KategoriID")
                        .HasColumnType("int");

                    b.Property<int?>("KitapAdedi")
                        .HasColumnType("int");

                    b.Property<string>("KitapAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("KitapAlindiMi")
                        .HasColumnType("bit");

                    b.Property<int?>("YazarID")
                        .HasColumnType("int");

                    b.HasKey("KitapID");

                    b.ToTable("TabloKitap");
                });

            modelBuilder.Entity("Akıllı_Kütüphane_Yönetim_Sistemi.db_vs_sinif.Kullanici", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.ToTable("TabloKullanici");
                });

            modelBuilder.Entity("Akıllı_Kütüphane_Yönetim_Sistemi.db_vs_sinif.OduncIslem", b =>
                {
                    b.Property<int>("IslemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IslemID"));

                    b.Property<DateTime?>("AlisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KitapID")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SonTeslimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TeslimTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("IslemID");

                    b.ToTable("TabloOduncIslemler");
                });

            modelBuilder.Entity("Akıllı_Kütüphane_Yönetim_Sistemi.db_vs_sinif.Rezervasyon", b =>
                {
                    b.Property<int>("RezervasyonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RezervasyonID"));

                    b.Property<int?>("KitapID")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnayDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TalepTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("RezervasyonID");

                    b.ToTable("TabloRezervasyon");
                });
#pragma warning restore 612, 618
        }
    }
}
